# Generated by Django 4.2.7 on 2023-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Cake', 'Cake'), ('Cookies', 'Cookies'), ('Muffins', 'Muffins')], max_length=50)),
                ('order_state', models.CharField(choices=[('Created', 'Created'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=50)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('branch', models.IntegerField()),
                ('customer', models.IntegerField()),
            ],
        ),
    ]
