version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: front-end/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: backend/project/Dockerfile
    volumes:
      - django_static_volume:/usr/src/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Raajteja@26
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres_data:
  django_static_volume:
